
export default {
    // STACK SCREEN
    HOME_STACK: "HOME_STACK",
    DASHBOARD_STACK: "DASHBOARD_STACK",
    SCAN_STACK: "SCAN_STACK",
    JOBS_STACK: "JOBS_STACK",
    SETTINGS_STACK: "SETTINGS_STACK",

    // MAIN SCREEN
    HOME_SCREEN: "HOME_SCREEN",
    DASHBOARD_SCREEN: "DASHBOARD_SCREEN",
    JOBS_SCREEN: "JOBS_SCREEN",
    SCAN_SCREEN: "SCAN_SCREEN",
    SETTINGS_SCREEN: "SETTINGS_SCREEN",
    TABS_ROUTE: "TABS_ROUTE",
    NEW_ORDER: "NEW_ORDER",
    JOB_DETAIL_SCREEN: "JOB_DETAIL_SCREEN",
    ESTIMATE_MATERIAL: "ESTIMATE_MATERIAL",
    MATERIALS_SCREEN: "MATERIALS_SCREEN",
    CHECK_IN: "CHECK_IN",
    CHECK_OUT: "CHECK_OUT",
    QUATATION_LIST: "QUATATION_LIST",
    QUATATION_DETAIL: "QUATATION_DETAIL",
    NEW_QUOTATION: "NEW_QUOTATION",

    // ADMIN SCREEN 
    ADMIN_JOBS_STACK: "ADMIN_JOBS_STACK",
    ADMIN_HOME_STACK: "HOME_STACK",

    ADMIN_HOME_SCREEN: "ADMIN_HOME_SCREEN",
    ADMIN_JOBS_SCREEN: "ADMIN_JOBS_SCREEN",
    // ADMIN_HOME: "ADMIN_HOME",
    ADMIN_JOB_DETAIL: "ADMIN_JOB_DETAIL",

    SPALSH_SCREEN: "Splash",
    LOGIN_SCREEN: "Login",
    FOROGOT_PASS_SCREEN: "FOROGOT_PASS_SCREEN",
    NEW_PASS_SCREEN: "NEW_PASS_SCREEN",
    INSTALLER_IMAGES: "INSTALLER_IMAGES",
    INSTALLER_REMARKS: "INSTALLER_REMARKS",
    CUSTOMER_IMAGES: "CUSTOMER_IMAGES",
    CUSTOMER_REMARK: "CUSTOMER_REMARK",
    PROFILE_SCREEN: "PROFILE_SCREEN",
    UPDATEPASSWORD_SCREEN: "UPDATEPASSWORD_SCREEN",
    SUPPORT_SCREEN: "SUPPORT_SCREEN",
    TERMSCONDITION_SCREEN: "TERMSCONDITION_SCREEN",
    REPORTING_ONLY: "REPORTING_ONLY",
    MY_CHATS: "MY_CHATS",
    ASSIGN_JOBS: "ASSIGN_JOBS",
    NEW_REPORTING: "NEW_REPORTING",
    EDIT_REPORTING: "EDIT_REPORTING",
    NEW_ACCIDENTAL_CLAIM: "NEW_ACCIDENTAL_CLAIM ",
    SURVEYOR_TAB: "SURVEYOR_TAB ",

    // SURVEYOR AND INSURANCE SCREEN 
    NEW_SURVEYOR: "NEW_SURVEYOR ",
    NEW_INSAURANCE: "NEW_INSAURANCE ",
    SURVEY_DETAIL: "SURVEY_DETAIL ",
    APPROVE_SURVEY_DETAIL: "APPROVE_SURVEY_DETAIL ",
    SERVICE_REPORT: "SERVICE_REPORT ",
    NEW_SURVEY_DETAIL: "NEW_SURVEY_DETAIL",
    NEXT_NEW_SURVEY_DETAIL: "NEXT_NEW_SURVEY_DETAIL",
    EDIT_SURVEY_DETAIL: "EDIT_SURVEY_DETAIL",
    EDIT_NEXT_SURVEY_DETAIL: "EDIT_NEXT_SURVEY_DETAIL",


}



